# Generated by Django 3.0.4 on 2020-04-22 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_clothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='description',
            field=models.CharField(default='description', max_length=100),
        ),
        migrations.AddField(
            model_name='clothes',
            name='imageLink',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='clothes',
            name='imageLink2',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='clothes',
            name='imageLink3',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='clothes',
            name='name',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='clothes',
            name='price',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
