# Generated by Django 3.0.4 on 2020-04-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200422_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='description',
            field=models.CharField(default='description', max_length=500),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='imageLink',
            field=models.CharField(default='default', max_length=500),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='imageLink2',
            field=models.CharField(default='default', max_length=500),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='imageLink3',
            field=models.CharField(default='default', max_length=500),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='name',
            field=models.CharField(default='default', max_length=500),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.CharField(default='default', max_length=500),
        ),
    ]
