# Generated by Django 3.0.4 on 2020-04-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200424_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='description',
            field=models.CharField(default='Материал: Полиэстер.........100%', max_length=500),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='imageLink',
            field=models.CharField(default='https://lichi-a.akamaihd.net/product/38348/thumbs/ff2c89c5a1f0a18fae140da8e2f31c8b_768_1024.jpg?v=0_3842912', max_length=500),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='imageLink2',
            field=models.CharField(default='https://lichi-a.akamaihd.net/product/38348/thumbs/d37653b27d106c02e1177fa12c1339da_768_1024.jpg?v=1_3842913', max_length=500),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='imageLink3',
            field=models.CharField(default='https://lichi-a.akamaihd.net/product/38348/thumbs/6c22e46babf91e34f540df33efa59661_768_1024.jpg?v=2_3842914', max_length=500),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='name',
            field=models.CharField(default='Платье The one by Lichi', max_length=500),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.CharField(default="30 950'", max_length=500),
        ),
    ]
