# Generated by Django 3.0.4 on 2020-04-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200424_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='imageLink',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='imageLink2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='imageLink3',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes', models.ManyToManyField(to='api.Clothes')),
            ],
        ),
    ]
