# Generated by Django 3.0.4 on 2020-04-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200425_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
