# Generated by Django 3.0.5 on 2020-04-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
